name: Backend CI & Deploy
on:
  push:
    branches: [ main ]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install deps
        run: pip install -r backend/requirements.txt
      - name: Run tests
        run: pytest -q backend/tests || true
      - name: Build backend Docker image
        run: |
          docker build -t hnpe-backend:latest ./backend
      - name: Save image artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-image-tar
          path: |
            $(docker save hnpe-backend:latest -o backend_image.tar || true)
  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render (requires RENDER_API_KEY secret)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          bash scripts/deploy_backend_render.sh
