name: Bot CI & Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Bot Docker
        run: docker build -t hnpe-bot:latest ./telegram
      - name: Deploy Bot to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          bash scripts/deploy_bot_render.sh
